# Generated by Django 5.2.5 on 2025-08-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Grocery', 'Grocery'), ('Home & Kitchen', 'Home & Kitchen')], max_length=50, null=True),
        ),
    ]
